export enum textTypes {
  TITLE_REGULAR = 'TITLE_REGULAR', //24px
  TITLE_BOLD = 'TITLE_BOLD',
  TITLE_LIGHT = 'TITLE_LIGHT',
  SUB_TITLE_REGULAR = 'SUB_TITLE_REGULAR', //20px
  SUB_TITLE_BOLD = 'SUB_TITLE_BOLD',
  SUB_TITLE_LIGHT = 'SUB_TITLE_LIGHT',
  BUTTON_REGULAR = 'BUTTON_REGULAR', //18px
  BUTTON_BOLD = 'BUTTON_BOLD',
  BUTTON_LIGHT = 'BUTTON_LIGHT',
  PARAGRAPH_REGULAR = 'PARAGRAPH_REGULAR', //14px
  PARAGRAPH_BOLD = 'PARAGRAPH_BOLD',
  PARAGRAPH_LIGHT = 'PARAGRAPH_LIGHT',
  PARAGRAPH_SMALL_REGULAR = 'PARAGRAPH_SMALL_REGULAR', //10px
  PARAGRAPH_SMALL_BOLD = 'PARAGRAPH_SMALL_BOLD',
  PARAGRAPH_SMALL_LIGHT = 'PARAGRAPH_SMALL_LIGHT',
}
